[package]
name = "upkg"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
alpm = "5"
reqwest = { version = "0.12", features = ["blocking"] }
termimad = "0.34.1"
indicatif = "0.17"
clap = { version = "4.5", features = ["derive"] }
