################### DISPLAY ####################
[display]
## ascii options: "PACMAN_DEFAULT", "PACMAN_SMALL", "NONE", or a file path

# ascii = "~/.config/pacfetch/ascii/example.txt"
ascii = "PACMAN_DEFAULT"
ascii_color = "yellow"


# Options: title, installed, upgradable, last_update, download_size, installed_size, net_upgrade_size,
# orphaned_packages, cache_size, disk, mirror_url, mirror_health
stats = [
    "title",
    "installed",
    "upgradable",
    "last_update",
    "download_size",
    "installed_size",
    "net_upgrade_size",
    "disk",
    "orphaned_packages",
    "cache_size",
    "mirror_url",
    "mirror_health",
]


[display.title]
# Title text: "default", "pacman_ver", "pacfetch_ver", custom string
text = "default"
text_color = "bright_yellow"
line_color = "none"

[display.glyph]
glyph = ": "



################### DISK ####################
[disk]
path = "/"


################### CACHE ####################
[cache]
# Set to 0 to always sync fresh
ttl_minutes = 15
