[display]
## ascii options: "PACMAN_DEFAULT", "PACMAN_SMALL", "NONE", or a file path
ascii = "PACMAN_DEFAULT"
# ascii = "~/.config/pacfetch/ascii/example.txt"

stats = [
    "installed",
    "upgradable",
    "last_update",
    "download_size",
    "installed_size",
    "net_upgrade_size",
    "orphaned_packages",
    "cache_size",
    "mirror_url",
    "mirror_health",
]
