[display]
## ascii options: "PACMAN_DEFAULT", "PACMAN_SMALL", "NONE", or a file path

# ascii = "~/.config/pacfetch/ascii/example.txt"
ascii = "PACMAN_DEFAULT"
ascii_color = "yellow"

# Stats to display, entries can be removed or reordered

# Options: installed, upgradable, last_update, download_size, installed_size net_upgrade_size, orphaned_packages,
# cache_size, mirror_url, mirror_health
stats = [
    "installed",
    "upgradable",
    "last_update",
    "download_size",
    "installed_size",
    "net_upgrade_size",
    "orphaned_packages",
    "cache_size",
    "mirror_url",
    "mirror_health",
]

[display.glyph]
glyph = ": "

[cache]
# Set to 0 to always sync fresh
ttl_minutes = 15
